export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';



// User actions 
export const SET_USER_LOCATION = 'SET_USER_LOCATION';


// Service actions
export const SERVICE_LOAD_REQUEST = 'SERVICE_LOAD_REQUEST';
export const SERVICE_LOAD_SUCCESS = 'SERVICE_LOAD_SUCCESS';
export const SERVICE_LOAD_ERROR = 'SERVICE_LOAD_ERROR';

export const SERVICES_LOAD_REQUEST = 'SERVICES_LOAD_REQUEST';
